apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "custom-mongodb.fullname" . }}
  labels:
    app: {{ template "custom-mongodb.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "custom-mongodb.fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "custom-mongodb.fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "custom-mongodb.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.internalPort }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.readinessProbe.tcpSocket.port }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.livenessProbe.tcpSocket.port }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        {{- end }}          
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: {{ template "custom-mongodb.fullname" . }}-data-volume
          mountPath: /data/db 
      volumes:
      - name: {{ template "custom-mongodb.fullname" . }}-data-volume
        persistentVolumeClaim:
          claimName: {{ template "custom-mongodb.fullname" . }}-pv-claim