apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "custom-mongodb.fullname" . }}-pv-claim
  labels:
    name: {{ template "custom-mongodb.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - {{ .Values.persistentVolume.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.capacity | quote }}
  selector:
    matchLabels:
      app: {{ template "custom-mongodb.fullname" . }}
      release: {{ .Release.Name }}
