apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "custom-mongodb.fullname" . }}-volume
  labels:
    app: {{ template "custom-mongodb.fullname" . }}
    release: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity | quote }}
  accessModes:
    - {{ .Values.persistentVolume.accessMode | quote }}
  nfs:
    server: {{ .Values.persistentVolume.nfsServer | quote }}
    # Exported path of your NFS server
    path: {{ .Values.persistentVolume.nfsPath | quote }}
