apiVersion: v1
description: Mongo Helm chart for Kubernetes.
name: mongo
version: 0.1.1
sources:
  - https://hub.docker.com/r/library/mongo/
maintainers:
  - name: Zaw Than Oo
    email: zawthanoo.1986@gmail.com
