# Default values for mongo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: mongo
  tag: 3.5.11
  pullPolicy: IfNotPresent

service:
  name: mongo
  tier: backend
  type: ClusterIP
  protocol: TCP
  externalPort: 27017
  internalPort: 27017

resources:
  limits:
    memory: 512Mi
  requests:
    memory: 128Mi

persistentVolume:
  capacity: 1Gi
  accessMode: ReadWriteMany
  nfsServer: 172.21.171.10
  nfsPath: /nfs

readinessProbe:
  enabled: true
  tcpSocket:
    port: 27017
  initialDelaySeconds: 60
  periodSeconds: 15

livenessProbe:
  enabled: true
  tcpSocket:
    port: 27017
  initialDelaySeconds: 15
  periodSeconds: 15  
  